### ISSUE TITLE
Special characters in VIKUNJA_DATABASE_PASSWORD

### ISSUE THREAD

**Issue by xrhstosmour** [go-vikunja/api#22]
I am trying to deploy via docker-compose the `vikunja/api` image, using as database PostgreSQL.
When the VIKUNJA_DATABASE_PASSWORD environment variable contains any special character like:
- `#`
- `$`
- `!`
- `@`

the deployment fails with the following error: `pq: password authentication failed for user "<my_database_user>" usermod: no changes`.
Only if i remove every special character the deployment suceeds.
I also tried escaping the password but nothing changed. A tool you can use for escaping the password can be found [here](https://www.urlencoder.org/).
Below you can find an example of the docker-compose.yml i tried:
``` 
vikunja_api:
  image: "vikunja/api:latest"
  container_name: "vikunja_api"
  restart: "unless-stopped"
  networks:
    - "public"
    - "local"
  ports:
    - "${VIKUNJA_API_PORT?Variable not set}:${VIKUNJA_API_PORT?Variable not set}"
  depends_on:
    - "postgresql"
  environment:
    - "VIKUNJA_DATABASE_TYPE=${VIKUNJA_DATABASE_TYPE?Variable not set}"
    - "VIKUNJA_DATABASE_HOST=${POSTGRESQL_SERVER?Variable not set}:${POSTGRESQL_PORT?Variable not set}"
    # Escape special charactes in passwords using the following tool: https://www.urlencoder.org/.
    - "VIKUNJA_DATABASE_PASSWORD=${VIKUNJA_DATABASE_ESCAPED_PASSWORD?Variable not set}"
    - "VIKUNJA_DATABASE_USER=${VIKUNJA_DATABASE_USER?Variable not set}"
    - "VIKUNJA_DATABASE_DATABASE=${VIKUNJA_DATABASE?Variable not set}"
    - "VIKUNJA_SERVICE_ENABLEREGISTRATION=${VIKUNJA_API_ENABLE_REGISTRATION?Variable not set}"
    - "VIKUNJA_SERVICE_TIMEZONE=${DOCKER_TIMEZONE?Variable not set}"
    - "PUID=${DOCKER_USER_UID?Variable not set}"
    - "PGID=${DOCKER_USER_UID?Variable not set}"
    - "VIKUNJA_FIRST_CHILD=${VIKUNJA_FIRST_CHILD?Variable not set}"
  volumes:
    - "vikunja_api_data:/app/vikunja/files"
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.vikunja_api.rule=Host(`${VIKUNJA_API_HOST?Variable not set}`) && PathPrefix(`/api/v1`, `/dav/`, `/.well-known/`)"
    - "traefik.http.routers.vikunja_api.service=vikunja_api"
    - "traefik.http.routers.vikunja_api.tls=true"
    - "traefik.http.routers.vikunja_api.entrypoints=web_secure"
    - "traefik.http.services.vikunja_api.loadbalancer.server.port=${VIKUNJA_API_PORT?Variable not set}"
```
How should i face this problem and proceed with the deployment?
Thank you in advance.

**Comment by xrhstosmour** [comment]
Just tested it, using the same PostgreSQL database, which works for all the other containers i use.
I forgot to say that i use a different port for the database which is exposed at the postgresql service at the docker-compose.yml as follows:
``` yml
ports:
  - "${POSTGRESQL_PORT?Variable not set}:${POSTGRESQL_PORT?Variable not set}"
expose:
  - "${POSTGRESQL_PORT?Variable not set}"
command: "-p ${POSTGRESQL_PORT?Variable not set}"
```
and provide it to the vikunja service at the docker-compose.yml, at the VIKUNJA_DATABASE_HOST environment variable as i described before:

``` yml
  environment:
    - "VIKUNJA_DATABASE_HOST=${POSTGRESQL_SERVER?Variable not set}:${POSTGRESQL_PORT?Variable not set}"
```
Furthermore i got again the same error, when doing what you suggested, as you can see below:

![image](https://user-images.githubusercontent.com/47348646/157524787-dfa75b3e-0bbe-4f26-9b5b-be63bcc6fdf6.png)

The config.yml file i used has the below format:
``` yml
database:
  type: "postgres"
  # The database existed vikunja user
  user: "my_database_user"
  # Database password containing the described special characters.
  password: "my_not_escaped_password_containing_#$!@"
  # Database host
  host: "PostgreSQL_IP:PostgreSQL_Port_Not_5432"
  # Database to use
  database: "my_database"

```
If i try to connect via pgAdmin to the above database, using the config.yml credentials without escaping anything, the connection succeeds. 
What am i doing wrong?

**Comment by kolaente** [comment]
Can you check with the postgres container if there's an error about a failed password attempt? I think you won't be able to reach the postgres container in your test with `docker run` since the two containers are not on the same network and the api container won't be able to reach any ports on exposed to the host by default.

I tried reproducing your problem with this compose file:

```yaml
version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 'passwordwith#$!@test'
      POSTGRES_USER: vikunja
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
  api:
    image: vikunja/api
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: 'passwordwith#$!@test'
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
    ports:
      - 3456:3456
    depends_on:
      - db
    restart: unless-stopped
```

but it failed to start with the error `Invalid interpolation format for "environment" option in service "db": "passwordwith#$!@test"` - I think docker compose's yaml parser is to blame here. I then moved the password to a .env file and it didn't work either. I don't know if the password it ended up setting in the db was the one I provided in the .env file though, probably not.

May I ask what your attack vector is here for using special characters in a db password? I think you could easily use a very long password (200+ characters) instead and be as secure, especially if you have your network properly secured so nobody can access it from the outside of your server.
