### ISSUE TITLE
VIKUNJA_DATABASE_HOST value  no taken into account

### ISSUE THREAD

**Issue by YasserAntonio** [go-vikunja/api#31]
Fresh install of vikunja/api:0.18.1 on raspb3 armv7-32

here is my docker-compose ( in a swarm with traffic) :

```
version: '3'

services:
  api:
    image: vikunja/api:0.18.1
    dns: 192.168.1.24
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: supersecret
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
    volumes:
      - /home/pi/vikunja/files:/app/vikunja/files
    networks:
      - traefik-local
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vikunja-api.rule=Host(`vikunja.ln`) && PathPrefix(`/api/v1`, `/dav/`, `/.well-known/`)"
        - "traefik.http.routers.vikunja-api.entrypoints=http"
      placement:
        constraints:
          - 'node.hostname == Hestia'

  frontend:
    image: vikunja/frontend:0.18.1
    dns: 192.168.1.24
    networks:
      - traefik-local
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vikunja-frontend.rule=Host(`vikunja.ln`)"
        - "traefik.http.routers.vikunja-frontend.entrypoints=web"
        - "traefik.http.services.vikunja-frontend.loadbalancer.server.port=80"
      placement:
        constraints:
          - 'node.hostname == Hestia'

  db:
    image: linuxserver/mariadb:alpine-10.5.12-r0-ls36
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=supersecret
      - TZ=Europe/Paris
      - MYSQL_DATABASE=vikunja #optional
      - MYSQL_USER=vikunja
      - MYSQL_PASSWORD=supersecret
    volumes:
      - /home/pi/vikunja/mariadb:/config
    deploy:
      placement:
        constraints:
          - 'node.hostname == Polymatheia'


networks:
  traefik-local:
    external: true
```

but keep having this log :

```
vikunja_api.1.z8bze8ch30o4@Hestia    | 2022-06-18T19:33:09.634767604Z: CRITICAL ▶ migration/Migrate 002 Migration failed: dial tcp 10.0.0.121:3306: connect: connection refused
vikunja_api.1.ayomtho5b9e5@Hestia    | usermod: no changes
vikunja_api.1.ayomtho5b9e5@Hestia    | 2022/06/18 19:33:17 Config File "config" Not Found in "[/app/vikunja /etc/vikunja /app/vikunja/.config/vikunja]"
vikunja_api.1.ayomtho5b9e5@Hestia    | 2022/06/18 19:33:17 Using default config.
vikunja_api.1.ayomtho5b9e5@Hestia    | 2022-06-18T19:33:17.430681988Z: CRITICAL ▶ migration/Migrate 002 Migration failed: dial tcp 10.0.0.121:3306: connect: connection refused
vikunja_api.1.yyk6pw0ev60c@Hestia    | usermod: no changes
vikunja_api.1.yyk6pw0ev60c@Hestia    | 2022/06/18 19:33:25 Config File "config" Not Found in "[/app/vikunja /etc/vikunja /app/vikunja/.config/vikunja]"
vikunja_api.1.yyk6pw0ev60c@Hestia    | 2022/06/18 19:33:25 Using default config.
vikunja_api.1.yyk6pw0ev60c@Hestia    | 2022-06-18T19:33:25.281242778Z: CRITICAL ▶ migration/Migrate 002 Migration failed: dial tcp 10.0.0.121:3306: connect: connection refused
vikunja_api.1.mziqxeyvocwk@Hestia    | usermod: no changes
vikunja_api.1.mziqxeyvocwk@Hestia    | 2022/06/18 19:33:33 Config File "config" Not Found in "[/app/vikunja /etc/vikunja /app/vikunja/.config/vikunja]"
vikunja_api.1.mziqxeyvocwk@Hestia    | 2022/06/18 19:33:33 Using default config.
vikunja_api.1.mziqxeyvocwk@Hestia    | 2022-06-18T19:33:33.520797942Z: CRITICAL ▶ migration/Migrate 002 Migration failed: dial tcp 10.0.0.121:3306: connect: connection refused
```
 
"10.0.0.121:3306" should be "db:3306" no ? 

still I can't make the api contact the db, I tried with postresql too just in case , same behavior :s 

any idea how solve this please ?

**Comment by kolaente** [comment]
It looks like the api container is only in the `traefik-local` docker network but the db container is not. Without much understanding of docker swarm or the `dns` option you have in your config, that looks like the two containers won't be able to talk to each other.
You should at least put the api and db container in the same docker network, similar to [the traefik example in the docs](https://vikunja.io/docs/full-docker-example/#example-with-traefik-2).

> "10.0.0.121:3306" should be "db:3306" no ?

The db driver might resolve the dns name to the IP.

**Comment by YasserAntonio** [comment]
I updated my docker-compose to make it closer to the [traefik2](https://vikunja.io/docs/full-docker-example/#example-with-traefik-2) exemple by removing , as you suggested the dns and by adding the default network on api and front end. Still in the exemple provided there is no network in the db service. 

here is the updated docker-compose : 

```
version: '3'

services:
  api:
    image: vikunja/api:0.18.1
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: supersecret
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
    volumes:
      - /home/pi/vikunja/files:/app/vikunja/files
    networks:
      - traefik-local
      - default
    depends_on:
      - db
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vikunja-api.rule=Host(`vikunja.ln`) && PathPrefix(`/api/v1`, `/dav/`, `/.well-known/`)"
        - "traefik.http.routers.vikunja-api.entrypoints=http"
      placement:
        constraints:
          - 'node.hostname == Hestia'

  frontend:
    image: vikunja/frontend:0.18.1
    networks:
      - traefik-local
      - default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vikunja-frontend.rule=Host(`vikunja.ln`)"
        - "traefik.http.routers.vikunja-frontend.entrypoints=web"
        - "traefik.http.services.vikunja-frontend.loadbalancer.server.port=80"
      placement:
        constraints:
          - 'node.hostname == Hestia'

  db:
    image: linuxserver/mariadb:alpine-10.5.12-r0-ls36
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=supersecret
      - TZ=Europe/Paris
      - MYSQL_DATABASE=vikunja #optional
      - MYSQL_USER=vikunja
      - MYSQL_PASSWORD=supersecret
    volumes:
      - /home/pi/vikunja/mariadb:/config
    deploy:
      placement:
        constraints:
          - 'node.hostname == Polymatheia'

networks:
  traefik-local:
    external: true
```


but I still have the same issue  :

```
vikunja_api.1.rtrpoco5hkos@Hestia    | usermod: no changes
vikunja_api.1.rtrpoco5hkos@Hestia    | 2022/06/18 20:48:10 Config File "config" Not Found in "[/app/vikunja /etc/vikunja /app/vikunja/.config/vikunja]"
vikunja_api.1.rtrpoco5hkos@Hestia    | 2022/06/18 20:48:10 Using default config.
vikunja_api.1.rtrpoco5hkos@Hestia    | 2022-06-18T20:48:10.089124251Z: CRITICAL ▶ migration/Migrate 002 Migration failed: dial tcp 10.0.0.121:3306: connect: connection refused
vikunja_api.1.euiyixqj7hxd@Hestia    | usermod: no changes
vikunja_api.1.euiyixqj7hxd@Hestia    | 2022/06/18 20:48:18 Config File "config" Not Found in "[/app/vikunja /etc/vikunja /app/vikunja/.config/vikunja]"
vikunja_api.1.euiyixqj7hxd@Hestia    | 2022/06/18 20:48:18 Using default config.
vikunja_api.1.euiyixqj7hxd@Hestia    | 2022-06-18T20:48:18.178238724Z: CRITICAL ▶ migration/Migrate 002 Migration failed: dial tcp 10.0.0.121:3306: connect: connection refused
```

 I checked that mariadb:10 was running  and it was.
