### ISSUE TITLE
[BUG] VIKUNJA_SERVICE_ENABLEREGISTRATION environment variable not being set

### ISSUE THREAD

**Issue by soderluk** [go-vikunja/api#81]
### Description

I'm using docker-compose to run vikunja, and everything works nicely, except that when I set the `VIKUNJA_SERVICE_ENABLEREGISTRATION=false` or `VIKUNJA_SERVICE_ENABLEREGISTRATION=0` it's still `VIKUNJA_SERVICE_ENABLEREGISTRATION='true'` in the container.

My docker-compose.yml file:
``` 
version: '3'

services:
  database:
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    container_name: vikunja_postgres
    env_file:
      - .env
    volumes:
      - vikunja_postgres:/var/lib/postgresql/data
    restart: always

  api:
    image: vikunja/api
    container_name: vikunja_api
    env_file:
      - .env
    volumes:
      - vikunja_api:/app/vikunja/files
    ports:
      - 3456:3456
    depends_on:
      - database
    restart: always

  frontend:
    image: vikunja/frontend
    container_name: vikunja_frontend
    ports:
      - 8081:80
    restart: always

volumes:
  vikunja_postgres:
  vikunja_api:
```
Here's the .env file:
```
POSTGRES_PASSWORD="secret"
POSTGRES_USER="vikunja"
POSTGRES_DB="vikunja"

VIKUNJA_DATABASE_HOST="vikunja_postgres"
VIKUNJA_DATABASE_TYPE="postgres"
VIKUNJA_DATABASE_PASSWORD="${POSTGRES_PASSWORD}"
VIKUNJA_DATABASE_USER="${POSTGRES_USER}"
VIKUNJA_DATABASE_DATABASE="${POSTGRES_DB}"
VIKUNJA_SERVICE_JWTSECRET="super secret"
VIKUNJA_SERVICE_FRONTENDURL="https://vikunja.domain.com/"
VIKUNJA_SERVICE_ENABLEREGISTRATION=false
```
Everything else is set correctly, but the `VIKUNJA_SERVICE_ENABLEREGISTRATION`.
Verified by `docker exec -it vikunja_api sh` and running `/app/vikunja # export`:
```
export HOME='/root'
export HOSTNAME='26d323421cb1'
export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
export PGID='1000'
export POSTGRES_DB='vikunja'
export POSTGRES_PASSWORD='secret'
export POSTGRES_USER='vikunja'
export PUID='1000'
export PWD='/app/vikunja'
export SHLVL='1'
export TERM='xterm'
export VIKUNJA_DATABASE_DATABASE='vikunja'
export VIKUNJA_DATABASE_HOST='vikunja_postgres'
export VIKUNJA_DATABASE_PASSWORD='secret'
export VIKUNJA_DATABASE_TYPE='postgres'
export VIKUNJA_DATABASE_USER='vikunja'
export VIKUNJA_SERVICE_ENABLEREGISTRATION='true'
export VIKUNJA_SERVICE_FRONTENDURL='https://vikunja.domain.com/'
export VIKUNJA_SERVICE_JWTSECRET='super secret'
export VIKUNJA_SERVICE_ROOTPATH='/app/vikunja/'
```

### Vikunja Frontend Version

latest

### Vikunja API Version

latest

### Can you reproduce the bug on the Vikunja demo site?

No
